package com.dandelion.bean;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private String authorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_url
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private String authorityUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_icon
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private String authorityIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_level
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer authorityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.parent_authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer parentAuthorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_status
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer authorityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_type
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer authorityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_time
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_id
     *
     * @return the value of authority.authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_id
     *
     * @param authorityId the value for authority.authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_name
     *
     * @return the value of authority.authority_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_name
     *
     * @param authorityName the value for authority.authority_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_url
     *
     * @return the value of authority.authority_url
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public String getAuthorityUrl() {
        return authorityUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_url
     *
     * @param authorityUrl the value for authority.authority_url
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityUrl(String authorityUrl) {
        this.authorityUrl = authorityUrl == null ? null : authorityUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_icon
     *
     * @return the value of authority.authority_icon
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public String getAuthorityIcon() {
        return authorityIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_icon
     *
     * @param authorityIcon the value for authority.authority_icon
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityIcon(String authorityIcon) {
        this.authorityIcon = authorityIcon == null ? null : authorityIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_level
     *
     * @return the value of authority.authority_level
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getAuthorityLevel() {
        return authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_level
     *
     * @param authorityLevel the value for authority.authority_level
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityLevel(Integer authorityLevel) {
        this.authorityLevel = authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.parent_authority_id
     *
     * @return the value of authority.parent_authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getParentAuthorityId() {
        return parentAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.parent_authority_id
     *
     * @param parentAuthorityId the value for authority.parent_authority_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setParentAuthorityId(Integer parentAuthorityId) {
        this.parentAuthorityId = parentAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_status
     *
     * @return the value of authority.authority_status
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getAuthorityStatus() {
        return authorityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_status
     *
     * @param authorityStatus the value for authority.authority_status
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityStatus(Integer authorityStatus) {
        this.authorityStatus = authorityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_type
     *
     * @return the value of authority.authority_type
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getAuthorityType() {
        return authorityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_type
     *
     * @param authorityType the value for authority.authority_type
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setAuthorityType(Integer authorityType) {
        this.authorityType = authorityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_id
     *
     * @return the value of authority.create_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_id
     *
     * @param createId the value for authority.create_id
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_name
     *
     * @return the value of authority.create_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_name
     *
     * @param createName the value for authority.create_name
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_time
     *
     * @return the value of authority.create_time
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_time
     *
     * @param createTime the value for authority.create_time
     *
     * @mbg.generated Fri Sep 20 17:47:20 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}