package com.dandelion.bean;

import java.io.Serializable;

public class WorkOrderType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.type_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.type_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.type_status
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private Byte typeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.procedure
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private String procedure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.create_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.create_time
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order_type.create_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.type_id
     *
     * @return the value of work_order_type.type_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.type_id
     *
     * @param typeId the value for work_order_type.type_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.type_name
     *
     * @return the value of work_order_type.type_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.type_name
     *
     * @param typeName the value for work_order_type.type_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.type_status
     *
     * @return the value of work_order_type.type_status
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public Byte getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.type_status
     *
     * @param typeStatus the value for work_order_type.type_status
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setTypeStatus(Byte typeStatus) {
        this.typeStatus = typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.procedure
     *
     * @return the value of work_order_type.procedure
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public String getProcedure() {
        return procedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.procedure
     *
     * @param procedure the value for work_order_type.procedure
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setProcedure(String procedure) {
        this.procedure = procedure == null ? null : procedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.create_id
     *
     * @return the value of work_order_type.create_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.create_id
     *
     * @param createId the value for work_order_type.create_id
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.create_time
     *
     * @return the value of work_order_type.create_time
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.create_time
     *
     * @param createTime the value for work_order_type.create_time
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_type.create_name
     *
     * @return the value of work_order_type.create_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_type.create_name
     *
     * @param createName the value for work_order_type.create_name
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeId=").append(typeId);
        sb.append(", typeName=").append(typeName);
        sb.append(", typeStatus=").append(typeStatus);
        sb.append(", procedure=").append(procedure);
        sb.append(", createId=").append(createId);
        sb.append(", createTime=").append(createTime);
        sb.append(", createName=").append(createName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 这是Mybatis Generator拓展插件生成的类(请勿删除).
     * This class corresponds to the database table work_order_type
     *
     * @mbg.generated
     * @author generator
     */
    public static class Builder {
        /**
         * 这是Mybatis Generator拓展插件生成的属性(请勿删除).
         * This field corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        private WorkOrderType obj;

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder() {
            this.obj = new WorkOrderType();
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder typeId(Integer typeId) {
            obj.typeId = typeId;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder typeName(String typeName) {
            obj.typeName = typeName;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder typeStatus(Byte typeStatus) {
            obj.typeStatus = typeStatus;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder procedure(String procedure) {
            obj.procedure = procedure;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder createId(Integer createId) {
            obj.createId = createId;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder createTime(String createTime) {
            obj.createTime = createTime;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public Builder createName(String createName) {
            obj.createName = createName;
            return this;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public WorkOrderType build() {
            return this.obj;
        }
    }

    /**
     * 这是Mybatis Generator拓展插件生成的枚举(请勿删除).
     * This class corresponds to the database table work_order_type
     *
     * @mbg.generated
     * @author generator
     */
    public enum Column {
        typeId("type_id"),
        typeName("type_name"),
        typeStatus("type_status"),
        procedure("procedure"),
        createId("create_id"),
        createTime("create_time"),
        createName("create_name");

        /**
         * 这是Mybatis Generator拓展插件生成的属性(请勿删除).
         * This field corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        private final String column;

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public String value() {
            return this.column;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public String getValue() {
            return this.column;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
         * This method corresponds to the database table work_order_type
         *
         * @mbg.generated
         * @author generator
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}