package com.dandelion.dao.generator;

import com.dandelion.bean.WorkOrderType;
import com.dandelion.bean.WorkOrderTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkOrderTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    long countByExample(WorkOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int deleteByExample(WorkOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int insert(WorkOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int insertSelective(WorkOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    List<WorkOrderType> selectByExample(WorkOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    WorkOrderType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WorkOrderType record, @Param("example") WorkOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int updateByExample(@Param("record") WorkOrderType record, @Param("example") WorkOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int updateByPrimaryKeySelective(WorkOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated Tue Oct 29 16:01:58 CST 2019
     */
    int updateByPrimaryKey(WorkOrderType record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table work_order_type
     *
     * @mbg.generated
     * @author generator
     */
    WorkOrderType selectOneByExample(WorkOrderTypeExample example);
}